server:
  port: 8000
gateway:
  #Valid values are guava(for local), redis
  cacheMethod: ${CACHE_METHOD:guava}
  redis:
    #Will not be used if cacheMethod is guava
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
